# initial gitlab ci configuration 
# content is extended from ./gitlab-cicd 

variables: 
    initialvar: test
    IMAGE_NAME: gitlab-registry.proxym-group.net/adem.bouallegui/sonarqube-teams-notifier
    IMAGE_TAG: server
    
stages:
    - dockerise 
    - build 
    - integrate 
    - startserver


# work on tag dockerise
dockerise_sonarqube_debug:
    stage: dockerise
    tags:
      - docker 
    image:
      name: gcr.io/kaniko-project/executor:debug
      entrypoint: [""]
    rules:
       - if: '$CI_COMMIT_TAG =~ /dockerise/' 
    before_script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    script:
        - /kaniko/executor --context $CI_PROJECT_DIR --single-snapshot --dockerfile $CI_PROJECT_DIR/CICD-configs/Docker/global_Dockerfile --destination $IMAGE_NAME:$IMAGE_TAG



package_sonar_plugin:
    stage: build
    tags:
        - docker 
    image: gitlab-registry.proxym-group.net/docker/maven:3.6.3-jdk-11
    before_script: 
        - echo "packaging teams notifier sonarqube plugin"
    script: 
        - cd $CI_PROJECT_DIR/plugin_src/
        - mvn clean package
    artifacts:
        paths:
          - $CI_PROJECT_DIR/plugin_src/dir 
        expire_in: 1h 
#    rules:
#       - if: '$CI_COMMIT_TAG =~ /^release-\d+\.\d+\.\d+$/'
    only: 
        - disabled 



# job to reach k8s pod for sonarqube 
#  k8s container is reached since we are using service typeof LoadBalancer 

update_sonarqube: 
    stage: integrate 
    tags:
      - docker 
    # this will be chnaged  by specific ssh docker image 
    image: alpine:latest 
    before_script:
        # setting ssh 
        - apk add --no-cache openssh-client sshpass
    script:
        # clean plugins and shutdown sonarqube server 
        - sshpass -p 'root' ssh  -o StrictHostKeyChecking=no root@172.16.110.36 ' bash /root/shutdown-server.sh && rm -rf /opt/sonarqube/extensions/*.jar'
        # get jar and copy it 
        - sshpass -p 'root' scp ${PLUGIN_JAR_PATH} root@172.16.110.36:/opt/sonarqube/extensions/plugins/teams_notifier.jar
        # restart the sonarqube server 
        - sshpass -p 'sonar' ssh sonarqube@172.16.110.36 'cd /home/sonarqube/ && . ./run.sh'
        # add post to teams plugin in order to inform about server status 
        # restart the server 
    only:
        - disabled



