# initial POC for SonarQube Sandbox 
# initial gitlab ci configuration 
# content is extended from ./gitlab-cicd 

variables: 
    initialvar: test
    IMAGE_NAME: gitlab-registry.proxym-group.net/adem.bouallegui/sonarqube-teams-notifier
    IMAGE_TAG: server
    
stages:
    - dockerise 
    - build 
    - integrate 
    - debug


# work on tag dockerise
dockerise_sonarqube_debug:
    stage: dockerise
    tags:
      - docker 
    image:
      name: gcr.io/kaniko-project/executor:debug
      entrypoint: [""]
    rules:
       - if: '$CI_COMMIT_TAG =~ /dockerise/' 
    before_script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    script:
        - /kaniko/executor --context $CI_PROJECT_DIR --single-snapshot --dockerfile $CI_PROJECT_DIR/CICD-configs/Docker/global_Dockerfile --destination $IMAGE_NAME:$IMAGE_TAG



package_sonar_plugin:
    stage: build
    tags:
        - docker 
    image: gitlab-registry.proxym-group.net/docker/maven:3.6.3-jdk-11
    before_script: 
        - echo "packaging teams notifier sonarqube plugin"
    script: 
        - cd $CI_PROJECT_DIR/plugin_src/
        - mvn clean package -DskipTests
    artifacts:
        paths:
          - $CI_PROJECT_DIR/plugin_src/target/sonar-teams-notifier-1.3.3.jar
        expire_in: 1h 
    rules:
       - if: '$CI_COMMIT_TAG =~ /^release-\d+\.\d+\.\d+$/'




# job to reach k8s pod for sonarqube 
#  k8s container is reached since we are using service typeof LoadBalancer 

update_sonarqube: 
    variables:
        GIT_STRATEGY: none
        NEW_PLUGIN_FULL_PATH: $CI_PROJECT_DIR/plugin_src/target/sonar-teams-notifier-1.3.3.jar
    stage: integrate 
    tags:
      - docker 
    # this will be chnaged  by specific ssh docker image 
    image: alpine:latest 
    needs:
        - job: package_sonar_plugin
          artifacts: true
    before_script:
        # setting ssh 
        - apk add --no-cache openssh-client sshpass
    script:
        # running shutdown server script 
        # please read the shutdow-server script in order to get the full goal of the script 
        - sshpass -p 'root' ssh  -o StrictHostKeyChecking=no root@172.16.110.36 ' bash /root/shutdown-server.sh '
        # get jar and copy it 
        - sshpass -p 'root' scp ${NEW_PLUGIN_FULL_PATH} root@172.16.110.36:/opt/sonarqube/extensions/plugins/teams_notifier.jar
        # restart the sonarqube server 
        - sshpass -p 'sonar' ssh sonarqube@172.16.110.36 'cd /home/sonarqube/ && . ./start-server.sh'
        # add post to teams plugin in order to inform about server status 
        # restart the server 
    rules:
       - if: '$CI_COMMIT_TAG =~ /^release-\d+\.\d+\.\d+$/'


# initial definition of live debug job 
launch_live_debug:
    stage: debug
    tags:
      - docker 
    # this image will be changed to dedicated job image
    image: alpine:latest 
    before_script:
        # setting ssh
        - apk add --no-cache openssh-client sshpass
    script: 
        # shutdown server 
        - sshpass -p 'root' ssh  -o StrictHostKeyChecking=no root@172.16.110.36 ' bash /root/shutdown-server.sh '
        # edit sonar.properties to modify live debug on port 8080
        - sshpass -p 'root' ssh  -o StrictHostKeyChecking=no root@172.16.110.36 ' bash /home/sonarqube/enable-live-debug.sh '
        # start server 
        - sshpass -p 'sonar' ssh sonarqube@172.16.110.36 'cd /home/sonarqube/ && . ./start-server.sh'
        # notify developer that server is waiting for ide link 
        # to be added in next milestone 
    rules:
       - if: '$CI_COMMIT_TAG =~ /live-debug/'
       
##################################################################""
# this is a debug job used to check gitlab  env variables 
gitlab_debug:
    stage: debug 
    tags:
        - docker
    image: alpine:latest
    before_script: 
        - echo "getting env variables "
    script:
        - echo $CI_PIPELINE_SOURCE	
        - echo $CI_COMMIT_AUTHOR
        - echo $CI_COMMIT_AUTHOR > content ; cat content
    only:
        - develop
