apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: ns-prx-18
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: gitlab-registry.proxym-group.net/adem.bouallegui/sonarqube-teams-notifier:stable
        ports:
        - containerPort: 9000
        - containerPort: 9092
        - containerPort: 8080
        - containerPort: 22
        - containerPort: 8000
      imagePullSecrets:
        - name: gitlab-auth
