apiVersion: v1
kind: Service 
metadata:
  name: sonar-service
  namespace: ns-prx-18
  labels:
    app: sonarqube
spec:
  selector:
    app: sonarqube
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
    name: http
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: debug
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: live-debug
  - port: 22
    targetPort: 22
    name: ssh
    protocol: TCP



